# Default values for kube-state-metrics-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: kube-state-metrics
namespace: kube-system
port: 10301
portName: metrics

replicas: 1

image:
  registry: quay.io
  repository: giantswarm/kube-state-metrics
  tag: v1.6.0

imageResizer:
  registry: quay.io
  repository: giantswarm/addon-resizer
  tag: 1.8.4

test:
  image:
    registry: quay.io
    repository: giantswarm/alpine-testing
    tag: 0.1.0
